// <auto-generated />
namespace WebSite_Galgnvegl.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddInfo_and_Promoter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddInfo_and_Promoter));
        
        string IMigrationMetadata.Id
        {
            get { return "201601070813031_AddInfo_and_Promoter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
